const GrosaryData = [
  {
    name: "Organic Basmati Rice",
    image: "https://cdn11.bigcommerce.com/s-dis4vxtxtc/images/stencil/1280x1280/products/3170/4915/Organic-Basmati-Rice-White-5KG-Offset_RIBAS2.5.sq__25474.1599544391.jpg?c=2?imbypass=on",
    price: 120,
    originalPrice: 150,
    description: "Long grain, aromatic, perfect for biryani or pulao.",
    brand: "Nature’s Basket",
    category: "Grains",
    rating: 4.6,
  },
  {
    name: "Sunflower Oil - 1L",
    image: "https://5.imimg.com/data5/SELLER/Default/2022/9/PE/IY/DN/65816739/1l-freedom-refined-sunflower-oil-500x500.jpg",
    price: 110,
    originalPrice: 130,
    description: "Healthy, cholesterol-free refined oil.",
    brand: "Saffola",
    category: "Oils",
    rating: 4.3,
  },
  {
    name: "Tata Tea Gold 250g",
    image: "https://tse2.mm.bing.net/th/id/OIP.RZTJJ8gocTrqIucUMYB3YQAAAA?pid=Api&P=0&h=180",
    price: 85,
    originalPrice: 95,
    description: "Strong aroma-rich blend of Assam and long leaves.",
    brand: "Tata",
    category: "Beverages",
    rating: 4.4,
  },
  {
    name: "Amul Butter 500g",
    image: "https://karthika.sg/image/catalog/products/SLURRP/product-oI_VztiWqH97EnWeXAI2s-0.jpg",
    price: 220,
    originalPrice: 250,
    description: "Rich, creamy, perfect for breakfast toast.",
    brand: "Amul",
    category: "Dairy",
    rating: 4.8,
  },
  {
    name: "Chakki Atta 5kg",
    image: "https://www.jiomart.com/images/product/600x600/491349659/chakki-atta-5-kg-product-images-o491349659-p491349659-0-202204281316.jpg",
    price: 225,
    originalPrice: 260,
    description: "100% whole wheat, stone ground flour.",
    brand: "Fortune",
    category: "Flour",
    rating: 4.5,
  },
  {
    name: "Himalayan Rock Salt Grinder 100g",
    image: "https://5.imimg.com/data5/ECOM/Default/2022/6/LB/DC/JI/2398936/himalayanpinksaltgrinder-100g-1-1000x1000.png",
    price: 140,
    originalPrice: 160,
    description: "Pink salt with a built-in grinder, rich in minerals.",
    brand: "Tata Himalayan",
    category: "Spices",
    rating: 4.7,
  },
  {
    name: "Raw Pressery Cold Pressed Orange Juice 1L",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=85,metadata=none,w=480,h=480/app/images/products/full_screen/pro_287023.jpg?ts=1643862405",
    price: 180,
    originalPrice: 199,
    description: "Fresh, vitamin-rich juice with no added sugar.",
    brand: "Raw Pressery",
    category: "Beverages",
    rating: 4.6,
  },
  {
    name: "Kellogg's Muesli Nuts Delight 500g",
    image: "https://m.media-amazon.com/images/I/81XXckaHi8L._SL1500_.jpg",
    price: 270,
    originalPrice: 310,
    description: "Wholesome cereal with almonds, raisins, and crunchy oats.",
    brand: "Kellogg's",
    category: "Breakfast",
    rating: 4.5,
  },
  {
    name: "Brookside Dark Chocolate - Blueberry 100g",
    image: "https://www.snrshopping.com/upload/product_details/5fa1e8c2c9e9a_1604446402.jpg",
    price: 190,
    originalPrice: 210,
    description: "Luxury chocolate with exotic fruit center.",
    brand: "Brookside",
    category: "Snacks",
    rating: 4.6,
  },
  {
    name: "Nestle A+ Slim Milk 1L",
    image: "https://m.media-amazon.com/images/I/717U2Jbqb+L._SL1500_.jpg",
    price: 75,
    originalPrice: 82,
    description: "Low-fat milk, ideal for fitness-focused lifestyles.",
    brand: "Nestlé",
    category: "Dairy",
    rating: 4.4,
  },
  {
    name: "Figaro Extra Virgin Olive Oil 500ml",
    image: "https://m.media-amazon.com/images/I/71fHUkl7R2L._SL1001_.jpg",
    price: 299,
    originalPrice: 350,
    description: "Mediterranean olive oil, perfect for salads & sautéing.",
    brand: "Figaro",
    category: "Oils",
    rating: 4.7,
  },
  {
    name: "Quaker Oats 1kg",
    image: "https://m.media-amazon.com/images/I/81m6APEiHoL._SL1500_.jpg",
    price: 145,
    originalPrice: 170,
    description: "Classic breakfast oats for heart health.",
    brand: "Quaker",
    category: "Breakfast",
    rating: 4.5,
  },
  {
    name: "Mother's Recipe Mixed Pickle 500g",
    image: "http://cdn.shopify.com/s/files/1/0341/6519/4888/products/mixedpickle_1200x1200.png?v=1631130502",
    price: 110,
    originalPrice: 130,
    description: "Authentic Indian pickle with bold spices.",
    brand: "Mother’s Recipe",
    category: "Condiments",
    rating: 4.5,
  },
  {
    name: "24 Mantra Organic Turmeric Powder 200g",
    image: "https://tse4.mm.bing.net/th/id/OIP.2_1ujwIrXWNj0UxcffgsqQHaK9?pid=Api&P=0&h=180",
    price: 85,
    originalPrice: 100,
    description: "Pure turmeric with high curcumin content.",
    brand: "24 Mantra",
    category: "Spices",
    rating: 4.6,
  },
  {
    name: "Urban Platter Premium Almonds 500g",
    image: "https://m.media-amazon.com/images/I/61W8cJMz7bL._SL1200_.jpg",
    price: 375,
    originalPrice: 420,
    description: "Crunchy, export-quality Californian almonds.",
    brand: "Urban Platter",
    category: "Dry Fruits",
    rating: 4.8,
  },
];

export default GrosaryData;
