const GrosaryData = [
  {
    name: "Organic Basmati Rice",
    image: "https://m.media-amazon.com/images/I/61SRn5cDiOL._SX679_.jpg",
    price: 120,
    originalPrice: 150,
    description: "Long grain, aromatic, perfect for biryani or pulao.",
    brand: "Nature’s Basket",
    category: "Grains",
    rating: 4.6,
  },
  {
    name: "Sunflower Oil - 1L",
    image: "https://m.media-amazon.com/images/I/71VmHSc8N9L._SX679_.jpg",
    price: 110,
    originalPrice: 130,
    description: "Healthy, cholesterol-free refined oil.",
    brand: "Saffola",
    category: "Oils",
    rating: 4.3,
  },
  {
    name: "Tata Tea Gold 250g",
    image: "https://m.media-amazon.com/images/I/71Q9q6Zy2BL._SX679_.jpg",
    price: 85,
    originalPrice: 95,
    description: "Strong aroma-rich blend of Assam and long leaves.",
    brand: "Tata",
    category: "Beverages",
    rating: 4.4,
  },
  {
    name: "Amul Butter 500g",
    image: "https://m.media-amazon.com/images/I/71WoQWMepWL._SX679_.jpg",
    price: 220,
    originalPrice: 250,
    description: "Rich, creamy, perfect for breakfast toast.",
    brand: "Amul",
    category: "Dairy",
    rating: 4.8,
  },
  {
    name: "Chakki Atta 5kg",
    image: "https://m.media-amazon.com/images/I/81r4UEnO7qL._SX679_.jpg",
    price: 225,
    originalPrice: 260,
    description: "100% whole wheat, stone ground flour.",
    brand: "Fortune",
    category: "Flour",
    rating: 4.5,
  },
  {
    name: "Himalayan Rock Salt Grinder 100g",
    image: "https://m.media-amazon.com/images/I/71jeAf7BrmL._SX679_.jpg",
    price: 140,
    originalPrice: 160,
    description: "Pink salt with a built-in grinder, rich in minerals.",
    brand: "Tata Himalayan",
    category: "Spices",
    rating: 4.7,
  },
  {
    name: "Raw Pressery Cold Pressed Orange Juice 1L",
    image: "https://m.media-amazon.com/images/I/61R4LdaNH+L._SX679_.jpg",
    price: 180,
    originalPrice: 199,
    description: "Fresh, vitamin-rich juice with no added sugar.",
    brand: "Raw Pressery",
    category: "Beverages",
    rating: 4.6,
  },
  {
    name: "Kellogg's Muesli Nuts Delight 500g",
    image: "https://m.media-amazon.com/images/I/71xU0yA3HUL._SX679_.jpg",
    price: 270,
    originalPrice: 310,
    description: "Wholesome cereal with almonds, raisins, and crunchy oats.",
    brand: "Kellogg's",
    category: "Breakfast",
    rating: 4.5,
  },
  {
    name: "Brookside Dark Chocolate - Blueberry 100g",
    image: "https://m.media-amazon.com/images/I/61WYvUFiqwL._SX679_.jpg",
    price: 190,
    originalPrice: 210,
    description: "Luxury chocolate with exotic fruit center.",
    brand: "Brookside",
    category: "Snacks",
    rating: 4.6,
  },
  {
    name: "Nestle A+ Slim Milk 1L",
    image: "https://m.media-amazon.com/images/I/71KTCsE7knL._SX679_.jpg",
    price: 75,
    originalPrice: 82,
    description: "Low-fat milk, ideal for fitness-focused lifestyles.",
    brand: "Nestlé",
    category: "Dairy",
    rating: 4.4,
  },
  {
    name: "Figaro Extra Virgin Olive Oil 500ml",
    image: "https://m.media-amazon.com/images/I/71rkW4lDlaL._SX679_.jpg",
    price: 299,
    originalPrice: 350,
    description: "Mediterranean olive oil, perfect for salads & sautéing.",
    brand: "Figaro",
    category: "Oils",
    rating: 4.7,
  },
  {
    name: "Quaker Oats 1kg",
    image: "https://m.media-amazon.com/images/I/81aLrb4sSDL._SX679_.jpg",
    price: 145,
    originalPrice: 170,
    description: "Classic breakfast oats for heart health.",
    brand: "Quaker",
    category: "Breakfast",
    rating: 4.5,
  },
  {
    name: "Mother's Recipe Mixed Pickle 500g",
    image: "https://m.media-amazon.com/images/I/91SzT3U2WFL._SX679_.jpg",
    price: 110,
    originalPrice: 130,
    description: "Authentic Indian pickle with bold spices.",
    brand: "Mother’s Recipe",
    category: "Condiments",
    rating: 4.5,
  },
  {
    name: "24 Mantra Organic Turmeric Powder 200g",
    image: "https://m.media-amazon.com/images/I/71KDvDJmDHL._SX679_.jpg",
    price: 85,
    originalPrice: 100,
    description: "Pure turmeric with high curcumin content.",
    brand: "24 Mantra",
    category: "Spices",
    rating: 4.6,
  },
  {
    name: "Urban Platter Premium Almonds 500g",
    image: "https://m.media-amazon.com/images/I/81Ba8R97u0L._SX679_.jpg",
    price: 375,
    originalPrice: 420,
    description: "Crunchy, export-quality Californian almonds.",
    brand: "Urban Platter",
    category: "Dry Fruits",
    rating: 4.8,
  },
];

export default GrosaryData;
